### ISSUE TITLE
[question] active cooling, petrol?

### ISSUE THREAD

**Issue by elmakong** [oni-guides/oni-guides#1]
for the usage example on active-cooling-without-steel.png it is shown of it using water and suggesting using polluted water for the heat transfer between liquid and gas. my question is, why not using petrol as it has lower freezing point (as stated in https://oxygennotincluded.gamepedia.com/Liquid) and better heat transfer. or maybe using supercoolant (if you feeling rich)

**Comment by kyldvs** [comment]
The main reason is that a thermo aquatuner always cools by 14°C no matter what liquid goes through it. This means you get more efficient cooling when the liquid has a higher specific heat capacity. Water and Polluted water have a higher specific heat capacity than everything except super coolant.

If you need to cool something really cold you need to use something else though, because the various versions of water will freeze. That is when you would want to switch to petroleum (or ethanol if you have it).

And yeah supercoolant beats everything
